import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Individual Tests (18 items)
        {
            name: 'Complete Blood Count (CBC)',
            description: 'Comprehensive blood test that evaluates overall health and detects blood disorders, infections, and anemia. Measures red blood cells, white blood cells, platelets, and hemoglobin levels.',
            category: 'test',
            subcategory: 'blood',
            price: 350.0,
            originalPrice: 500.0,
            discountPercentage: 30,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: true,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'HBA1C (Diabetes Test)',
            description: 'Measures average blood sugar levels over the past 2-3 months. Essential for diabetes diagnosis, monitoring, and management. Helps assess long-term glucose control.',
            category: 'test',
            subcategory: 'diabetes',
            price: 450.0,
            originalPrice: 600.0,
            discountPercentage: 25,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: true,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            name: 'Lipid Profile',
            description: 'Comprehensive cholesterol test measuring total cholesterol, HDL, LDL, and triglycerides. Essential for heart health assessment and cardiovascular risk evaluation.',
            category: 'test',
            subcategory: 'heart',
            price: 400.0,
            originalPrice: 550.0,
            discountPercentage: 27,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: true,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Thyroid Profile (TSH, T3, T4)',
            description: 'Complete thyroid function assessment including TSH, T3, and T4 hormones. Detects hyperthyroidism, hypothyroidism, and other thyroid disorders affecting metabolism.',
            category: 'test',
            subcategory: 'thyroid',
            price: 500.0,
            originalPrice: 700.0,
            discountPercentage: 29,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 1,
            isPopular: true,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            name: 'Liver Function Test (LFT)',
            description: 'Comprehensive liver health assessment measuring enzymes, proteins, and bilirubin levels. Detects liver damage, hepatitis, and monitors liver function.',
            category: 'organ_test',
            subcategory: 'liver',
            price: 380.0,
            originalPrice: 520.0,
            discountPercentage: 27,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            name: 'Kidney Function Test (KFT)',
            description: 'Evaluates kidney health through creatinine, BUN, and electrolyte measurements. Essential for detecting kidney disease and monitoring renal function.',
            category: 'organ_test',
            subcategory: 'kidney',
            price: 420.0,
            originalPrice: 580.0,
            discountPercentage: 28,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Vitamin D Test',
            description: 'Measures Vitamin D levels crucial for bone health, immune function, and overall well-being. Detects deficiency that can lead to osteoporosis and weakened immunity.',
            category: 'test',
            subcategory: 'vitamins',
            price: 800.0,
            originalPrice: 1200.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Vitamin B12 Test',
            description: 'Assesses Vitamin B12 levels essential for nerve function, red blood cell formation, and DNA synthesis. Detects deficiency causing anemia and neurological issues.',
            category: 'test',
            subcategory: 'vitamins',
            price: 650.0,
            originalPrice: 900.0,
            discountPercentage: 28,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            name: 'Iron Studies',
            description: 'Comprehensive iron assessment including serum iron, ferritin, and transferrin levels. Diagnoses iron deficiency anemia and iron overload disorders.',
            category: 'test',
            subcategory: 'blood',
            price: 550.0,
            originalPrice: 750.0,
            discountPercentage: 27,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'ESR & CRP',
            description: 'Inflammation markers detecting infections, autoimmune diseases, and inflammatory conditions. ESR and CRP levels indicate body\'s inflammatory response.',
            category: 'test',
            subcategory: 'inflammation',
            price: 300.0,
            originalPrice: 450.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Urine Routine & Microscopy',
            description: 'Complete urine analysis detecting urinary tract infections, kidney disorders, and metabolic conditions. Includes physical, chemical, and microscopic examination.',
            category: 'test',
            subcategory: 'urine',
            price: 200.0,
            originalPrice: 300.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 12,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Blood Sugar (Fasting)',
            description: 'Measures glucose levels after overnight fasting. Primary screening test for diabetes and prediabetes. Essential for diabetes monitoring and management.',
            category: 'test',
            subcategory: 'diabetes',
            price: 150.0,
            originalPrice: 250.0,
            discountPercentage: 40,
            homeCollectionAvailable: true,
            reportDeliveryHours: 12,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            name: 'Blood Sugar (PP)',
            description: 'Post-meal glucose test measuring blood sugar levels 2 hours after eating. Helps diagnose diabetes and evaluate glucose tolerance.',
            category: 'test',
            subcategory: 'diabetes',
            price: 150.0,
            originalPrice: 250.0,
            discountPercentage: 40,
            homeCollectionAvailable: true,
            reportDeliveryHours: 12,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Creatinine',
            description: 'Kidney function marker measuring waste product levels in blood. Essential for detecting kidney disease and monitoring renal health.',
            category: 'test',
            subcategory: 'kidney',
            price: 180.0,
            originalPrice: 280.0,
            discountPercentage: 36,
            homeCollectionAvailable: true,
            reportDeliveryHours: 12,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            name: 'Blood Pressure Monitoring',
            description: 'Comprehensive blood pressure assessment for hypertension detection and cardiovascular risk evaluation. Includes multiple readings for accuracy.',
            category: 'test',
            subcategory: 'heart',
            price: 100.0,
            originalPrice: 200.0,
            discountPercentage: 50,
            homeCollectionAvailable: false,
            reportDeliveryHours: 2,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            name: 'Calcium & Phosphorus',
            description: 'Bone health assessment measuring calcium and phosphorus levels. Essential for detecting osteoporosis, parathyroid disorders, and bone metabolism issues.',
            category: 'test',
            subcategory: 'bone',
            price: 320.0,
            originalPrice: 480.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Electrolyte Panel',
            description: 'Measures sodium, potassium, and chloride levels for fluid balance assessment. Critical for detecting dehydration, kidney disorders, and electrolyte imbalances.',
            category: 'test',
            subcategory: 'blood',
            price: 280.0,
            originalPrice: 400.0,
            discountPercentage: 30,
            homeCollectionAvailable: true,
            reportDeliveryHours: 12,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            name: 'Protein Total & Albumin',
            description: 'Liver and kidney function assessment through protein levels. Detects malnutrition, liver disease, and kidney disorders affecting protein metabolism.',
            category: 'test',
            subcategory: 'protein',
            price: 250.0,
            originalPrice: 380.0,
            discountPercentage: 34,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 1,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },

        // Health Packages (10 items)
        {
            name: 'Comprehensive Health Checkup',
            description: 'Complete health assessment including CBC, lipid profile, diabetes screening, thyroid function, liver & kidney tests, vitamins, and cardiac markers. Perfect annual health checkup.',
            category: 'package',
            subcategory: 'comprehensive',
            price: 2500.0,
            originalPrice: 4000.0,
            discountPercentage: 38,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 25,
            isPopular: true,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Diabetes Package',
            description: 'Comprehensive diabetes screening and monitoring package including HbA1c, fasting glucose, post-meal glucose, lipid profile, and kidney function tests.',
            category: 'package',
            subcategory: 'diabetes',
            price: 1200.0,
            originalPrice: 1800.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 8,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            name: 'Heart Health Package',
            description: 'Cardiovascular risk assessment including lipid profile, cardiac enzymes, ECG, blood pressure monitoring, and inflammation markers for complete heart health evaluation.',
            category: 'package',
            subcategory: 'heart',
            price: 1500.0,
            originalPrice: 2200.0,
            discountPercentage: 32,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 12,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'Women\'s Health Package',
            description: 'Comprehensive women\'s health screening including hormonal tests, thyroid function, bone health, anemia screening, and reproductive health markers.',
            category: 'package',
            subcategory: 'women',
            price: 1800.0,
            originalPrice: 2500.0,
            discountPercentage: 28,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 15,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Men\'s Health Package',
            description: 'Tailored men\'s health checkup including prostate markers, testosterone levels, cardiac risk assessment, diabetes screening, and vitamin analysis.',
            category: 'package',
            subcategory: 'men',
            price: 1600.0,
            originalPrice: 2300.0,
            discountPercentage: 30,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 14,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            name: 'Senior Citizen Package (60+)',
            description: 'Comprehensive health package for seniors including cardiac markers, bone health, kidney function, diabetes screening, and age-related health assessments.',
            category: 'package',
            subcategory: 'senior',
            price: 2200.0,
            originalPrice: 3200.0,
            discountPercentage: 31,
            homeCollectionAvailable: true,
            reportDeliveryHours: 72,
            testsIncluded: 20,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: 'Executive Health Checkup',
            description: 'Premium comprehensive health assessment for executives including advanced cardiac screening, stress markers, complete metabolic panel, and executive physical examination.',
            category: 'package',
            subcategory: 'executive',
            price: 3500.0,
            originalPrice: 5000.0,
            discountPercentage: 30,
            homeCollectionAvailable: true,
            reportDeliveryHours: 72,
            testsIncluded: 35,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            name: 'Basic Health Checkup',
            description: 'Essential health screening package including CBC, basic metabolic panel, liver function, kidney function, and diabetes screening for routine health monitoring.',
            category: 'package',
            subcategory: 'basic',
            price: 800.0,
            originalPrice: 1200.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 10,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Cancer Screening Package',
            description: 'Early cancer detection package including tumor markers, complete blood count, liver function, and specialized cancer screening tests for preventive healthcare.',
            category: 'package',
            subcategory: 'cancer',
            price: 2800.0,
            originalPrice: 4200.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 72,
            testsIncluded: 18,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            name: 'Allergy Panel Package',
            description: 'Comprehensive allergy testing including food allergies, environmental allergens, and respiratory allergens to identify triggers and manage allergic reactions.',
            category: 'package',
            subcategory: 'allergy',
            price: 2000.0,
            originalPrice: 3000.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 72,
            testsIncluded: 50,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },

        // Lifestyle Packages (7 items)
        {
            name: 'Diabetes Lifestyle Package',
            description: 'Specialized diabetes management package including glucose monitoring, HbA1c, lipid profile, kidney function, and dietary consultation for optimal diabetes control.',
            category: 'lifestyle',
            subcategory: 'diabetes',
            price: 1000.0,
            originalPrice: 1500.0,
            discountPercentage: 33,
            homeCollectionAvailable: true,
            reportDeliveryHours: 24,
            testsIncluded: 6,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Hypertension Management',
            description: 'Blood pressure management package including 24-hour BP monitoring, cardiac markers, kidney function, and lifestyle counseling for hypertension control.',
            category: 'lifestyle',
            subcategory: 'hypertension',
            price: 900.0,
            originalPrice: 1400.0,
            discountPercentage: 36,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 5,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            name: 'Weight Management Package',
            description: 'Comprehensive weight management assessment including thyroid function, metabolic panel, insulin resistance, and nutritional deficiency screening.',
            category: 'lifestyle',
            subcategory: 'weight',
            price: 1100.0,
            originalPrice: 1600.0,
            discountPercentage: 31,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 8,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Fitness Enthusiast Package',
            description: 'Athletic performance package including muscle health markers, vitamin levels, cardiac fitness assessment, and recovery indicators for fitness optimization.',
            category: 'lifestyle',
            subcategory: 'fitness',
            price: 1300.0,
            originalPrice: 1900.0,
            discountPercentage: 32,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 10,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            name: 'Stress & Anxiety Package',
            description: 'Mental health assessment including cortisol levels, neurotransmitter analysis, vitamin deficiencies affecting mood, and stress hormone evaluation.',
            category: 'lifestyle',
            subcategory: 'stress',
            price: 950.0,
            originalPrice: 1450.0,
            discountPercentage: 34,
            homeCollectionAvailable: true,
            reportDeliveryHours: 72,
            testsIncluded: 7,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Sleep Quality Package',
            description: 'Sleep disorder assessment including melatonin levels, sleep apnea markers, vitamin D, magnesium levels, and hormonal factors affecting sleep quality.',
            category: 'lifestyle',
            subcategory: 'sleep',
            price: 1150.0,
            originalPrice: 1700.0,
            discountPercentage: 32,
            homeCollectionAvailable: true,
            reportDeliveryHours: 72,
            testsIncluded: 8,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            name: 'Immunity Booster Package',
            description: 'Immune system evaluation including vitamin C, vitamin D, zinc levels, inflammatory markers, and complete blood count for optimal immunity assessment.',
            category: 'lifestyle',
            subcategory: 'immunity',
            price: 850.0,
            originalPrice: 1300.0,
            discountPercentage: 35,
            homeCollectionAvailable: true,
            reportDeliveryHours: 48,
            testsIncluded: 6,
            isPopular: false,
            isSafe: true,
            imageUrl: null,
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Apollo Diagnostics products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});